import { motion } from "framer-motion";
import mascotThinking from "/assets/mascotThinking.png";
import { useEffect, useState } from "react";

const models = [
  {
    name: "Chet 1.0",
    tier: "Basic",
    price: "Free",
    points: "5CC per question",
  },
  {
    name: "Chet 2.0",
    tier: "Standard",
    price: "$10/mo",
    points: "10CC per question",
  },
  {
    name: "Chet 3.0",
    tier: "Plus",
    price: "$20/mo",
    points: "15CC per question",
  },
  {
    name: "Chet 4.0",
    tier: "Pro",
    price: "$40/mo",
    points: "20C per question",
  },
  {
    name: "Chet 5.0",
    tier: "Ultra",
    price: "$80/mo",
    points: "25CC per question",
  },
];

export default function ChetModelOverlay({ onClose }: { onClose: () => void }) {
  const [remainingTime, setRemainingTime] = useState(5);

  const [infoOpen, setInfoOpen] = useState(false);
  const [showedTrialExpire, setShowedTrialExpire] = useState(false);

  const showModelsPage = () => {
    setShowedTrialExpire(true);
    let i = remainingTime;
    let interval = setInterval(() => {
      i--;
      setRemainingTime(i);
      console.log("remainingTime", remainingTime);
      if (i === 0) {
        clearInterval(interval);
      }
    }, 1000);
    return () => clearInterval(interval);
  };

  return (
    <>
      {!showedTrialExpire && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="bg-white p-8 rounded-2xl shadow-2xl w-[450px] text-center relative"
          >
            <h1 className="text-2xl font-bold mb-2 text-blue-700">
              Free Trial Expired
            </h1>
            <p className="text-gray-600 mb-6 text-left">
              Your free trial of Chet 2.0 has expired. You will be downgraded to
              Chet 1.0 for the remaining questions.
            </p>
            <button
              onClick={showModelsPage}
              className="absolute top-3 right-5 text-gray-500 hover:text-gray-700 text-xl"
            >
              ×
            </button>
          </motion.div>
        </div>
      )}
      {showedTrialExpire && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="bg-white p-8 rounded-2xl shadow-2xl w-[650px] text-center relative"
          >
            {infoOpen && (
              <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  className="bg-white p-8 rounded-2xl shadow-2xl w-[450px] text-center relative"
                >
                  <h1 className="text-2xl font-bold mb-2 text-blue-700">
                    About Chet Models
                  </h1>
                  <p className="text-gray-600 mb-6 text-left">
                    Chet models range from the most lighweight Chet 1.0 to the
                    most powerful Chet 5.0. Your model corresponds to the tier
                    of Chet to which you are subscribed.
                  </p>
                  <p className="text-gray-600 mb-6 text-left">
                    'CC' stands for 'Chet Coins.' Chet Coins are a measure of
                    your progress in your educational journey. Questions
                    generated by more powerful Chet models, being more advanced
                    and advancing your learning further, will be worth more Chet
                    Coins.
                  </p>
                  <p className="text-gray-600 mb-6 text-left">
                    Choose a model that suits your learning style.
                  </p>
                  <button
                    onClick={() => setInfoOpen(false)}
                    className="absolute top-3 right-5 text-gray-500 hover:text-gray-700 text-xl"
                  >
                    ×
                  </button>
                </motion.div>
              </div>
            )}

            {/* Close button */}
            <button
              onClick={() => setInfoOpen(true)}
              className="absolute top-3 right-4 text-blue-400 hover:text-gray-700 hover:border-gray-700 text-xl text-bold w-7 h-7 border-2 border-blue-400 rounded-full"
            >
              <div className="-translate-y-[1.5px]">i</div>
            </button>
            {/**/}
            {/* Mascot */}
            <div className="flex justify-center">
              <img
                src={mascotThinking}
                alt="Chet Gipette"
                className="w-32 mx-auto mb-4 rounded-xl"
              />

              <div>
                <h2 className="text-3xl font-bold mb-2 text-blue-700">
                  Choose Your Chet Model
                </h2>
                <p className="text-gray-600 mb-6">
                  Select a version of Chef Chet optimized for your learning
                  needs.
                </p>
              </div>
            </div>

            <div className="grid gap-3 text-left">
              {models.map((m, i) => (
                <motion.div
                  key={m.name}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className={
                    i == 0
                      ? "p-4 border border-blue-400 rounded-xl shadow-sm hover:shadow-md transition bg-blue-50 flex justify-between items-center"
                      : "p-4 border rounded-xl shadow-sm hover:shadow-md transition bg-gray-50 flex justify-between items-center"
                  }
                >
                  <div>
                    <p className="font-semibold text-lg">{m.name}</p>
                    <p className="text-gray-600 text-sm">{m.tier} Tier</p>
                  </div>
                  {i == 0 && (
                    <div className="flex-col justify-right text-right">
                      <p className="text-blue-700">
                        <em>Currently Active</em>
                      </p>
                    </div>
                  )}
                  <div className="flex-col justify-right text-right">
                    <p className="font-bold text-blue-700">{m.price}</p>
                    <p className="text-gray-600">{m.points}</p>
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="mt-8 flex justify-center">
              {/* Animated progress wheel */}
              {remainingTime > 0 && (
                <>
                  <motion.div
                    className="w-12 h-12 border-4 border-blue-400 border-t-transparent rounded-full"
                    animate={{ rotate: 360 }}
                    transition={{
                      repeat: Infinity,
                      duration: 1,
                      ease: "linear",
                    }}
                  />
                  <div className="text-center absolute translate-y-[11px]">
                    {remainingTime}
                  </div>
                </>
              )}
              {remainingTime === 0 && (
                <button
                  className="py-2 px-4 border rounded-xl shadow-sm hover:shadow-md transition bg-gray-50 flex justify-between items-center"
                  onClick={onClose}
                >
                  Close
                </button>
              )}
            </div>
          </motion.div>
        </div>
      )}
    </>
  );
}
